# Generated by Django 4.1 on 2022-09-04 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cbf_api", "0002_jogosporrodada_rename_numero_jogo_jogo_numero_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rodada",
            fields=[
                (
                    "numero",
                    models.IntegerField(
                        max_length=2, primary_key=True, serialize=False
                    ),
                ),
                (
                    "jogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cbf_api.jogo",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="JogosPorRodada",
        ),
    ]
