# Generated by Django 4.1 on 2022-09-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbf_api", "0003_rodada_delete_jogosporrodada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rodada",
            name="numero",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
