# Generated by Django 4.1 on 2022-09-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbf_api", "0004_alter_rodada_numero"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rodada",
            name="jogo",
        ),
    ]
