# Generated by Django 4.1 on 2022-09-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cbf_api", "0005_remove_rodada_jogo"),
    ]

    operations = [
        migrations.AddField(
            model_name="jogo",
            name="rodada",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="cbf_api.rodada",
            ),
        ),
    ]
