# Generated by Django 4.1 on 2022-09-04 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cbf_api", "0006_jogo_rodada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jogo",
            name="cidade",
            field=models.CharField(default="A definir", max_length=30),
        ),
        migrations.AlterField(
            model_name="jogo",
            name="estadio",
            field=models.CharField(default="A definir", max_length=30),
        ),
        migrations.AlterField(
            model_name="jogo",
            name="estado",
            field=models.CharField(default="--", max_length=2),
        ),
        migrations.AlterField(
            model_name="jogo",
            name="rodada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="cbf_api.rodada"
            ),
        ),
    ]
